### ISSUE TITLE
Add IPFS service that is peered to https://ipfs.network.thegraph.com/ipfs/

### ISSUE THREAD

**Issue by schmidsi** [StakeSquid/graphprotocol-mainnet-docker#20]
Currently, there is a single point of failure with https://ipfs.network.thegraph.com/ipfs/. Indexers should run their own node and peer to https://ipfs.network.thegraph.com/ipfs/ to increase resilience.

**Comment by trader-payne** [comment]
Hi Simon,
Unfortunately I cannot add an IPFS container as it triggers netscans in datacenters and this will lead to many people having their cloud accounts banned. :)
I haven't seen a solution that works, apart from setting firewall rules on the private network ports, which then disable certain actions from indexers such as `graph indexer status` command, etc.

**Comment by schmidsi** [comment]
Oh, that's bad. Thanks for the update. Shall we leave this issue open to investigate other options at a later point? Otherwise, feel free to close it.

**Comment by abarmat** [comment]
That one I shared is temporary (but seems it should work) until this one lands https://github.com/ipfs/kubo/issues/6932

**Comment by schmidsi** [comment]
For context here would be the config to setup an IPFS node to peer with The Graph's hosted service IPFS node: https://docs.ipfs.tech/how-to/peering-with-content-providers/#content-provider-list (thanks to Leo)

**Comment by leoyvens** [comment]
The peer ID of the network IPFS node (not hosted service) is `QmUBRCtHivKQCXNykUdtpnhqSCTVuaE6ajLXANFG8Etp7j`

**Comment by trader-payne** [comment]
I've seen reports that the flag doesn't stop it from net scanning. I'm willing to try it out but I need someone with a burner account that can afford to have their (baremetal) server (potentially) blocked in case this doesn't work.

**Comment by Chomtana** [comment]
I think flag `IPFS_PROFILE: server` works as I don't get any hetzner ban after using this flag

```yaml
  ipfs:
    image: ipfs/kubo:v0.18.1
    container_name: ipfs
    restart: unless-stopped
    environment:
      IPFS_PROFILE: server
    expose:
      - 5001
    ports:
      - 5001:5001
    volumes:
      - ipfs_data:/data/ipfs
      - ./ipfs-init.sh:/container-init.d/ipfs-init.sh
    networks:
      - monitor-net
```
